'use strict';
let express = require('express');
let router = express.Router();
let order_controller = require('../controllers/orderController.js');
router.get('/create', order_controller.order_create_get);
router.get('/createWithNewLists', order_controller.order_create_get_withNewLists);
router.post('/create', order_controller.order_create_post);
router.post('/createWithNewLists', order_controller.order_create_post);
router.get('/:id/delete', order_controller.order_delete_get);
router.post('/:id/delete', order_controller.order_delete_post);
router.get('/:id/update', order_controller.order_update_get);
router.post('/:id/update', order_controller.order_update_post);
router.get('/list/:daterange', order_controller.order_list);
router.get('/exportWithEmptyLocalId', order_controller.orders_exportWithEmptyLocalId);
router.get('/populatePaymentAccount', order_controller.populatePaymentAccount);
module.exports = router;
